### ISSUE TITLE
Error creating assets with spaces in path

### ISSUE THREAD

**Issue by mvsoder** [avereon/xenon#263]
java.lang.IllegalArgumentException: Illegal character in path at index 10: C:/Program Files/Xenon
at java.base/java.net.URI.create(Unknown Source)
at com.avereon.zevra@0.10-SNAPSHOT/com.avereon.util.FileUtil.findValidFolder(Unknown Source)
at com.avereon.xenon@1.8-SNAPSHOT/com.avereon.xenon.tool.AssetTool.open(Unknown Source)
at com.avereon.xenon@1.8-SNAPSHOT/com.avereon.xenon.ProgramTool.lambda$callToolReady$6(Unknown Source)
at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.URISyntaxException: Illegal character in path at index 10: C:/Program Files/Xenon
at java.base/java.net.URI$Parser.fail(Unknown Source)
at java.base/java.net.URI$Parser.checkChars(Unknown Source)
at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
at java.base/java.net.URI$Parser.parse(Unknown Source)
at java.base/java.net.URI.<init>(Unknown Source)

**Comment by mvsoder** [comment]
Fix in upstream dependency: https://github.com/avereon/zevra/commit/a0f45ea60adc56581d9b7bdbb676c9ca2a8b32cf
