### ISSUE TITLE
Mac OS - Update command does not run as part of update cycle

### ISSUE THREAD

**Issue by mvsoder** [avereon/xenon#70]
Apparently there is an exception attempting to start the updater:

java.io.IOException: Cannot run program "/var/folders/8b/s7vvmx2x66zb7d28sgkq80_c0000gp/T/xenon-updater/bin/java" (in directory "/var/folders/8b/s7vvmx2x66zb7d28sgkq80_c0000gp/T/xenon-updater"): error=17, File exists
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.avereon.xenon/com.avereon.xenon.ProgramShutdownHook.run(ProgramShutdownHook.java:202)
Caused by: java.io.IOException: error=17, File exists
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 2 more

**Comment by mvsoder** [comment]
java.io.IOException: Cannot run program "/var/folders/8b/s7vvmx2x66zb7d28sgkq80_c0000gp/T/xenon-updater/bin/java" (in directory "/var/folders/8b/s7vvmx2x66zb7d28sgkq80_c0000gp/T/xenon-updater"): error=17, File exists
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.avereon.xenon/com.avereon.xenon.ProgramShutdownHook.run(ProgramShutdownHook.java:202)
Caused by: java.io.IOException: error=17, File exists
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 2 more

**Comment by mvsoder** [comment]
Also after starting the updater manually the updater was not able to start a process either:

java.io.IOException: Cannot run program "/private/var/folders/8b/s7vvmx2x66zb7d28sgkq80_c0000gp/T/elevate": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.avereon.zenna/com.avereon.zenna.ElevatedHandler.startElevatedUpdater(ElevatedHandler.java:149)
	at com.avereon.zenna/com.avereon.zenna.ElevatedHandler.start(ElevatedHandler.java:48)
	at com.avereon.zenna/com.avereon.zenna.Program.executeTask(Program.java:405)
	at com.avereon.zenna/com.avereon.zenna.Program.runTasksNormally(Program.java:365)
	at com.avereon.zenna/com.avereon.zenna.Program.runTasks(Program.java:311)
	at com.avereon.zenna/com.avereon.zenna.Program.runTasksFromReader(Program.java:307)
	at com.avereon.zenna/com.avereon.zenna.Program.runTasksFromStream(Program.java:303)
	at com.avereon.zenna/com.avereon.zenna.Program.runTasksFromFile(Program.java:299)
	at com.avereon.zenna/com.avereon.zenna.Program.execute(Program.java:217)
	at com.avereon.zenna/com.avereon.zenna.Program$Runner.run(Program.java:194)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 12 more

**Comment by mvsoder** [comment]
It appears that this issues is related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-5049299. The workaround in Java 11 is to set the system property "jdk.lang.Process.launchMechanism" to "FORK". There were also changes in this area in Java 12 so it might work better with Java 12+.

**Comment by mvsoder** [comment]
This is working under Java 11
