### ISSUE TITLE
The --status command line option causes a running instance to show

### ISSUE THREAD

**Issue by mvsoder** [avereon/xenon#73]
The --status command line options should show the program status and exit without causing a running instance to show or starting a new instance.

**Comment by mvsoder** [comment]
Also...cleanup this stack trace:
Programs/xenon/bin/java -m com.avereon.xenon --status
     __       _
\_/ |_  |\ | / \ |\ |
/ \ |__ | \| \_/ | \|

Xenon 0.9-SNAPSHOT
2019-09-19 10:07:20.398 [I] c.a.x.ProgramServer.start: Program server listening on port 43017 
Exception in Application init method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application init method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.avereon.xenon/com.avereon.xenon.Program.isRunning(Program.java:642)
	at com.avereon.xenon/com.avereon.xenon.Program.printStatus(Program.java:911)
	at com.avereon.xenon/com.avereon.xenon.Program.processControlCommands(Program.java:816)
	at com.avereon.xenon/com.avereon.xenon.Program.init(Program.java:239)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	... 2 more
Exception running application com.avereon.xenon.Program

**Comment by mvsoder** [comment]
Fixed with improved host/peer communication #81.
