### ISSUE TITLE
Cannot register mod icon due to IllegalAccessException

### ISSUE THREAD

**Issue by mvsoder** [avereon/xenon#79]
2019-09-26 17:59:05.456 [E] c.a.x.IconLibrary.getIconRenderer: Unable to create icon: mouse-maze 
java.lang.IllegalAccessException: class com.avereon.xenon.IconLibrary$IconConfig (in module com.avereon.xenon) cannot access class com.avereon.mouse.MouseMazeIcon (in module com.avereon.mouse) because module com.avereon.mouse does not export com.avereon.mouse to module com.avereon.xenon
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:490)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.avereon.xenon/com.avereon.xenon.IconLibrary$IconConfig.newInstance(IconLibrary.java:118)
	at com.avereon.xenon/com.avereon.xenon.IconLibrary.getIconRenderer(IconLibrary.java:77)
	at com.avereon.xenon/com.avereon.xenon.IconLibrary.getIcon(IconLibrary.java:51)
	at com.avereon.xenon/com.avereon.xenon.IconLibrary.getIcon(IconLibrary.java:43)
	at com.avereon.xenon/com.avereon.xenon.IconLibrary.getIcon(IconLibrary.java:39)
	at com.avereon.mouse/com.avereon.mouse.MouseMod.register(MouseMod.java:48)
	at com.avereon.xenon/com.avereon.xenon.update.ProductManager.callModRegister(ProductManager.java:1057)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
	at com.avereon.xenon/com.avereon.xenon.update.ProductManager.start(ProductManager.java:897)
	at com.avereon.xenon/com.avereon.xenon.Program.doStartTasks(Program.java:384)

**Comment by mvsoder** [comment]
Unable to reproduce this exception.
Xenon 1.0-SNAPSHOT
Linux x64
Java: 13

**Comment by mvsoder** [comment]
I was able to reproduce this and it looks like there was a conflict between an installed version of the mod as a package and the compiled version on the classpath. This conflict is understandable and the way to resolve it is don't have the same module loaded from two sources. Maybe in the future I should ensure that does not happen during development.

**Comment by mvsoder** [comment]
This check is already in place to avoid double loading in development.

**Comment by mvsoder** [comment]
The loading process did have a slight issue trying to double load a service. This has been remedied also.
