### ISSUE TITLE
The "Download and store updates" causes RuntimeException: Method not implemented

### ISSUE THREAD

**Issue by mvsoder** [avereon/xenon#9]
Caused by: java.lang.RuntimeException: Method not implemented yet. at com.xeomar.xenon/com.xeomar.xenon.update.UpdateManager.cacheSelectedUpdates(UpdateManager.java:575) at com.xeomar.xenon/com.xeomar.xenon.update.ProgramUpdateManager$StoreUpdates.call(ProgramUpdateManager.java:300) at com.xeomar.xenon/com.xeomar.xenon.update.ProgramUpdateManager$StoreUpdates.call(ProgramUpdateManager.java:285) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

**Comment by mvsoder** [comment]
This issue no longer applies due the the changes in #85
