### ISSUE TITLE
ResourceException: Resource must be opened to be loaded

### ISSUE THREAD

**Issue by mvsoder** [avereon/xenon#93]
The following exception shows in the notice pane at startup:
java.lang.RuntimeException: com.avereon.xenon.resource.ResourceException: Resource must be opened to be loaded: program:task
com.avereon.xenon.resource.ResourceException: Resource must be opened to be loaded: program:guide
	at com.avereon.xenon@1.0-SNAPSHOT/com.avereon.xenon.resource.ResourceManager$ResourceTask.call(ResourceManager.java:1576)
	at com.avereon.xenon@1.0-SNAPSHOT/com.avereon.xenon.resource.ResourceManager$ResourceTask.call(ResourceManager.java:1543)

**Comment by mvsoder** [comment]
This ended up being caused by a difference between "created" resources and "open" resources. The logic behind creating a resource has been improved and is no longer dependent on the open resources collection.
